Update Chard_Installer
rust

diff --git a/Chard_Installer b/Chard_Installer
--- a/Chard_Installer
+++ b/Chard_Installer
@@ -424,7 +424,8 @@ PACKAGES=(
     "dconf|0.49.0|tar.xz|https://download.gnome.org/sources/dconf/0.49/dconf-0.49.0.tar.xz|dconf-0.49.0|meson"
     "gsettings-desktop-schemas|49.0|tar.xz|https://download.gnome.org/sources/gsettings-desktop-schemas/49/gsettings-desktop-schemas-49.0.tar.xz|gsettings-desktop-schemas-49.0|meson"
     "shared-mime-info|2.4|tar.gz|https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.4/shared-mime-info-2.4.tar.gz|shared-mime-info-2.4|meson"
-    "rustc|1.82.0|tar.gz|https://static.rust-lang.org/dist/rustc-1.82.0-src.tar.gz|rustc-1.82.0-src|pythonwrap"
+    "rust|1.82.0|tar.gz|https://static.rust-lang.org/dist/rust-1.82.0-x86_64-unknown-linux-gnu.tar.gz|rust-1.82.0-x86_64|rust-prebuilt"
+    "rust|1.82.0|tar.gz|https://static.rust-lang.org/dist/rust-1.82.0-aarch64-unknown-linux-gnu.tar.gz|rust-1.82.0-aarch64|rust-prebuilt"
     "glycin|2.0.0|tar.gz|https://gitlab.gnome.org/GNOME/glycin/-/archive/2.0.0/glycin-2.0.0.tar.gz|glycin-2.0.0|meson"
     "gdk-pixbuf|2.44.1|tar.xz|https://download.gnome.org/sources/gdk-pixbuf/2.44/gdk-pixbuf-2.44.1.tar.xz|gdk-pixbuf-2.44.1|meson"
     "appstream-glib|0.8.3|tar.xz|https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.8.3.tar.xz|appstream-glib-0.8.3|meson"
@@ -737,8 +738,19 @@ case \"$BUILDSYS\" in
         \"/usr/bin/python3.13\" setup.py build
         \"/usr/bin/python3.13\" setup.py install --prefix=/usr
         ;;
-   pythonwrap)
-        ./configure
+  rust-prebuilt)
+        if [ -d /usr/lib/x86_64-linux-gnu ]; then
+            DIR="rust-1.82.0-x86_64"
+        elif [ -d /usr/lib/aarch64-linux-gnu ]; then
+            DIR="rust-1.82.0-aarch64"
+        else
+            echo "Cannot find x86_64 or aarch64 lib directories"
+            exit 1
+        fi
+    
+        cd /var/tmp/build/$DIR
+        chmod +x install.sh
+        ./install.sh --prefix=/usr --without=rust-docs
         ;;
     pythonbuild)
         cd /var/tmp/build/$DIR
