Update Chard_Installer
minor fix

diff --git a/Chard_Installer b/Chard_Installer
--- a/Chard_Installer
+++ b/Chard_Installer
@@ -306,9 +306,13 @@ for pkg in "${PACKAGES[@]}"; do
 
     echo "[+] Building $NAME-$VERSION in chroot${RESET}"
     sudo chroot "/usr/local/chard" /bin/bash -c "
-    
-
-cd /var/tmp/build/$DIR
+# autodetect extracted folder
+cd /var/tmp/build
+SRC_DIR=\$(find . -maxdepth 1 -type d -name '${NAME}*' | head -n1)
+if [[ -z \"\$SRC_DIR\" ]]; then
+    echo 'Source directory for $NAME not found'; exit 1
+fi
+cd \$SRC_DIR
 
 ARCH=\$(uname -m)
 case \"\$ARCH\" in
@@ -318,7 +322,6 @@ case \"\$ARCH\" in
 esac
 
 GCC_DIR=/usr/\$CHOST/gcc-bin/14
-export MAGIC="/usr/share/misc/magic.mgc"
 export CC=\$GCC_DIR/\$CHOST-gcc
 export CXX=\$GCC_DIR/\$CHOST-g++
 export AR=\$GCC_DIR/gcc-ar
@@ -330,13 +333,7 @@ export PATH=/usr/\$CHOST/gcc-bin/14:/usr/bin:/bin:/usr/local/bin
 export LD_LIBRARY_PATH=\"${LD_LIBRARY_PATH:+\$LD_LIBRARY_PATH:}/usr/lib64\"
 export PERL5LIB=/usr/local/lib/perl5/site_perl/5.40.0:/usr/local/lib/perl5:$PERL5LIB
 export PYTHONPATH=/usr/lib/python3.13/site-packages
-PYTHON="/bin/python3"
-
-if [[ "$NAME" == "gtest" ]]; then
-    cd /var/tmp/build/${DIR}
-else
-    cd /var/tmp/build/$DIR
-fi
+PYTHON='/bin/python3'
 
 case \"$BUILDSYS\" in
     gnu)
@@ -352,27 +349,26 @@ case \"$BUILDSYS\" in
         ;;
     perl-core)
         sh Configure -des -Dprefix=/usr
-        make -j$(nproc)
+        make -j\$(nproc)
         make install
         ;;
     cmake)
         cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_GMOCK=OFF
-        cmake --build build -j$(nproc)
+        cmake --build build -j\$(nproc)
         cmake --install build
         ;;
-     meson)
+    meson)
         rm -rf build
         meson setup build --prefix=/usr
         ninja -C build
         ninja -C build install
         ;;
-      python)
-        cd /var/tmp/build/$DIR
-        setup.py build
-        setup.py install --prefix=/usr
+    python)
+        \$PYTHON setup.py build
+        \$PYTHON setup.py install --prefix=/usr
         ;;
     *)
-        echo \"Unknown build system: $BUILDSYS\"
+        echo 'Unknown build system: $BUILDSYS'
         exit 1
         ;;
 esac
@@ -509,18 +505,19 @@ mkdir -p $CHARD_ROOT/usr/share/sandbox
 
 cat > "$CHARD_ROOT/etc/sandbox.conf" <<'EOF'
 SANDBOX_BASHRC="/usr/local/chard/usr/share/sandbox/sandbox.bashrc"
-SANDBOX_D="/usr/local/chard//etc/sandbox.d"
+SANDBOX_D="/usr/local/chard/etc/sandbox.d"
 ns-mount-off
 ns-pid-off
 ns-ipc-off
 ns-net-off
 ns-user-off
+EOF
 
-cat <<'EOF' > "$CHARD_ROOT/usr/share/sandbox/sandbox.bashrc"
+cat > "$CHARD_ROOT/usr/share/sandbox/sandbox.bashrc" <<EOF
 export HOME="$CHARD_ROOT/root"
 export USER="chronos"
 export LOGNAME="chronos"
-export PATH="$CHARD_ROOT/usr/bin:$CHARD_ROOT/bin:$PATH"
+export PATH="$CHARD_ROOT/usr/bin:$CHARD_ROOT/bin:\$PATH"
 EOF
 
 sed -i '1s|.*|#!/usr/local/chard/usr/lib/portage/python3.13/ebuild.sh|' \
