Update Chard_Installer
rb

diff --git a/Chard_Installer b/Chard_Installer
--- a/Chard_Installer
+++ b/Chard_Installer
@@ -237,7 +237,6 @@ PACKAGES=(
     "pcre2|10.46|tar.gz|https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.46/pcre2-10.46.tar.gz|pcre2-10.46|gnu"
     "glib|2.86.0|tar.xz|https://download.gnome.org/sources/glib/2.86/glib-2.86.0.tar.xz|glib-2.86.0|meson"
     "pkg-config|0.29.2|tar.gz|https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz|pkg-config-0.29.2|gnu"
-    "meson|1.9.0|tar.gz|https://github.com/mesonbuild/meson/releases/download/1.9.0/meson-1.9.0.tar.gz|meson-1.9.0|meson"
 
 )
 mkdir -p "$BUILD_DIR"
@@ -249,9 +248,22 @@ for pkg in "${PACKAGES[@]}"; do
     ARCHIVE="$NAME-$VERSION.$EXT"
 
     echo "${RESET}${GREEN}[+] Downloading $NAME-$VERSION "
-    sudo curl -L --progress-bar -o "$BUILD_DIR/$ARCHIVE" "$URL"
 
-    echo "[+] Extracting $NAME-$VERSION ${RESET}${YELLOW}"
+    attempt=1
+    while true; do
+        sudo curl -L --progress-bar -o "$BUILD_DIR/$ARCHIVE" "$URL" && break
+
+        echo "${RED}[!] Download failed for $NAME-$VERSION (attempt $attempt/$MAX_RETRIES), retrying in $RETRY_DELAY seconds..."
+        (( attempt++ ))
+
+        if (( attempt > MAX_RETRIES )); then
+            echo "${BOLD}${RED}[!] Failed to download $NAME-$VERSION after $MAX_RETRIES attempts. Aborting.${RESET}"
+            exit 1
+        fi
+        sleep $RETRY_DELAY
+    done
+
+    echo "${RESET}${YELLOW}[+] Extracting $NAME-$VERSION"
     case "$EXT" in
         tar.gz|tgz)
             sudo tar -xzf "$BUILD_DIR/$ARCHIVE" -C "$BUILD_DIR" \
@@ -276,7 +288,7 @@ done
 for pkg in "${PACKAGES[@]}"; do
     IFS="|" read -r NAME VERSION EXT URL DIR BUILDSYS <<< "$pkg"
     
-    echo "[+] Mounting Chard Chroot"
+    echo "${RESET}${GREEN}[+] Mounting Chard Chroot${RESET}"
     mountpoint -q "$CHARD_ROOT/proc"    || sudo mount -t proc proc "$CHARD_ROOT/proc"
     mountpoint -q "$CHARD_ROOT/sys"     || sudo mount -t sysfs sys "$CHARD_ROOT/sys"
     mountpoint -q "$CHARD_ROOT/dev"     || sudo mount --bind /dev "$CHARD_ROOT/dev"
@@ -337,13 +349,15 @@ case \"$BUILDSYS\" in
         cmake --build build -j$(nproc)
         cmake --install build
         ;;
-    meson)
+     meson)
+        rm -rf build
         meson setup build --prefix=/usr
         ninja -C build
         ninja -C build install
         ;;
       python)
         /bin/python3 -m pip install --prefix=/usr .
+        ;;
     *)
         echo \"Unknown build system: $BUILDSYS\"
         exit 1
@@ -360,7 +374,6 @@ echo "${RESET}${MAGENTA}[+] Finished building $NAME-$VERSION${RESET}"
         sudo cp /usr/local/make "$CHARD_ROOT/usr/bin/make"
         echo "${GREEN}[+] Replaced symlink with real make binary in Chard Root${RESET}"
     fi
-
 
     echo
 
